dougnoel/sentinel

lombok.config, pom.xml
Complete clean up.
Included classpath-integrity profile report on common classpath errors.
mvn -Pclasspath-integrity
=> GH-1:  Clean up maven (test fails)

pom.xml, src/main/java/com/dougnoel/sentinel/steps/BaseSteps.java, src/main/java/com/dougnoel/sentinel/steps/VerificationSteps.java
=> Steps are not static

README.md, pom.xml
Changed version to SNAPSHOT version and updated readme for future releases.
=> Updating for release.

src/main/java/com/dougnoel/sentinel/configurations/Configuration.java, src/main/java/com/dougnoel/sentinel/elements/Element.java, src/main/java/com/dougnoel/sentinel/elements/dropdowns/SelectElement.java, src/main/java/com/dougnoel/sentinel/elements/tables/Table.java, src/main/java/com/dougnoel/sentinel/pages/Page.java, src/main/java/com/dougnoel/sentinel/steps/BaseSteps.java, src/main/java/com/dougnoel/sentinel/steps/SelectSteps.java, src/main/java/com/dougnoel/sentinel/steps/SelectVerificationSteps.java, src/main/java/com/dougnoel/sentinel/steps/VerificationSteps.java, src/test/java/com/herokuapp/JavascriptAlertsPage.yml, src/test/java/features/251 Verification Steps.feature, src/test/java/features/287 Select Verification Steps.feature, src/test/java/features/Base Steps Tests.feature
Fixes #287 
- revise selection of cell elements in table rows. 
- add table methods. 
- fix reset for header elements. 
- add SERE and NoSuchFrameException catching in element find logic (when searching through fram
es). 
- Add methods to select element. 
- add selectverificationsteps class to utilize new select element methods. 
- add step to accept or close js alert.
=> 287 Fix uncaught StaleElementReferenceException and add multiple enhancements

src/main/java/com/dougnoel/sentinel/elements/dropdowns/SelectElement.java, src/main/java/com/dougnoel/sentinel/elements/tables/Table.java, src/main/java/com/dougnoel/sentinel/steps/SelectVerificationSteps.java, src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java, src/test/java/com/dougnoel/sentinel/elements/ElementTests.java, src/test/java/features/287 Select Verification Steps.feature, src/test/java/features/Table Tests.feature
#305 
- add Table Verification step for getting specific cell data
- edit method in table to fetch column data faster using xpath. 
- add usage of step in table steps feature to cover new code.
=> add table verification step for getting specific cell data

pom.xml
=> add exclusion for offending library

src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java
=> modify gherkin matching text for a step in order to remove ambiguity.

docs/test/table.html
add buttons on html table rows to send alerts. will be used to verify table click steps
=> add buttons in html table

docs/test/radiobutton.html
=> making link downloadable

docs/test/table.html
Add empty table column for tests in other branch
=> add empty column in table.html

src/main/java/com/dougnoel/sentinel/elements/Element.java, src/main/java/com/dougnoel/sentinel/elements/tables/Table.java, src/main/java/com/dougnoel/sentinel/steps/DownloadVerificationSteps.java, src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java, src/main/java/com/dougnoel/sentinel/steps/VerificationSteps.java, src/test/java/com/herokuapp/DragAndDropPage.yml, src/test/java/features/251 Verification Steps.feature, src/test/java/features/Table Tests.feature
- add location getter on element
- add column location checking method on table
- add verification step for element relative location
- add tests
=> 371 location

src/main/java/com/dougnoel/sentinel/steps/TableSteps.java
address #379  
add ability to use stored values in clickAssociatedLinkInTable table step
=> 379 add ability to use stored values in clickAssociatedLinkInTable table step

src/main/java/com/dougnoel/sentinel/elements/Element.java
- update doesNotExist method to switch to root frame, look for element, then look in any iframes before determining if an element does not exist on the page
=> Update Element.doesNotExist to account for iframes on pages

docs/test/multiUploadTest.html
A simple multiple file upload test page with a multi input. It doesn't perform actual uploads, but allows the user to pass the information to the uploader, and it will return the file names chosen and verify the passed string does in fact count for multiple files. For single file and/or drag and drop testing https://the-internet.herokuapp.com/upload can be used.
=> Multiple file upload test page with sanitization on input for html display

src/main/java/com/dougnoel/sentinel/elements/tables/Table.java, src/main/java/com/dougnoel/sentinel/steps/SelectVerificationSteps.java, src/main/java/com/dougnoel/sentinel/steps/TableSteps.java, src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java, src/test/java/features/Table Tests.feature
Add functionality to click and verify stored values in tables
=> Table stored values

src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java, src/test/java/features/Table Tests.feature
Fix #426 
fix logging in table verification step. fix xpaths in feature file to be not prone to intermittent failure.
=> Fix Table Tests instability

src/main/java/com/dougnoel/sentinel/configurations/Time.java, src/main/java/com/dougnoel/sentinel/elements/tables/Table.java, src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java, src/test/java/com/dougnoel/sentinel/elements/ElementTests.java, src/test/java/features/Table Tests.feature
Address #430 
Add Table method for waiting a given amount of time for a cell to have or not have given text. Add step definition to use that method. Add unit tests.
=> 430 table wait

docs/test/table.html
=> Updated the table page for new tests

src/main/java/com/dougnoel/sentinel/elements/Element.java, src/main/java/com/dougnoel/sentinel/files/CsvFile.java, src/main/java/com/dougnoel/sentinel/steps/CsvSteps.java, src/test/java/features/386 CSV Steps.feature
#468 
- Add more csv verification steps
- Add exception types to element finding Waits
=> 468 more csv 2

src/main/java/com/dougnoel/sentinel/elements/Element.java, src/main/java/com/dougnoel/sentinel/elements/WindowsElement.java
Address #479 
Reduce number of wait operations on element finds in order to cycle through locators and frames way quicker.
=> Speedup element finds, especially in iframes

src/main/java/com/dougnoel/sentinel/steps/DownloadVerificationSteps.java, src/main/java/com/dougnoel/sentinel/system/DownloadManager.java, src/main/java/com/dougnoel/sentinel/webdrivers/WebDriverFactory.java, src/test/java/features/327 Download Verification Steps.feature
- Address #522 
- add optional parameter to downloadmanager's monitordownload that performs action after starting to listen for new files.
- add steps to click and verify file download in same step
=> Address download failures

docs/test/TestCSV.csv, docs/test/downloads.html
-Updated the Downloads Test Page to supply a download link
-Duplicated the header CSV test file to the downloads page
=> Add test csv file to downloads page

docs/test/downloads.html, src/test/java/io/github/dougnoel/DownloadsTestPage.yml
-Added element to yml
-Fixed a typo
=> Minor fixes

src/main/java/com/dougnoel/sentinel/elements/tables/Table.java, src/main/java/com/dougnoel/sentinel/steps/TableVerificationSteps.java, src/test/java/com/dougnoel/sentinel/elements/ElementTests.java, src/test/java/features/Table Tests.feature
Address #533 
add table method and table verification step in order to wait for all cells in column to have value. add integration and unit tests
=> 533 Wait for all table cells to have text

src/main/java/com/dougnoel/sentinel/configurations/Configuration.java, src/test/java/com/dougnoel/sentinel/configurations/ConfigurationTests.java
- address 535
- add methods for counting config values set during the session
- add unit tests
=> 535 add config count

src/main/java/com/dougnoel/sentinel/elements/tables/Table.java, src/test/java/features/Table Tests.feature
Updated the code to now reflect a check on unique values within a column.  Created a new scenario to check this.
=> 547 verify column cells are unique
